# Generated by Django 5.2.8 on 2025-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('department', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('seniority', models.TextField(null=True)),
                ('length', models.TextField(null=True)),
            ],
        ),
    ]
