# Generated by Django 5.2.8 on 2025-11-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='length',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
