# Generated by Django 5.2.8 on 2025-11-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_job_department_alter_job_length_alter_job_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(null=True),
        ),
    ]
